AllCops:
  Exclude:
    - tmp
    - vendor/**/*
Documentation:
  Enabled: false

LineLength:
  Description: 'Limit lines to a more generous 120 characters.'
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/BlockLength:
  Exclude:
    - 'spec/*.rb'
