AllCops:
  Exclude:
    - tmp
    - vendor/**/*
  TargetRubyVersion: 2.3
Documentation:
  Enabled: false

LineLength:
  Description: 'Limit lines to a more generous 120 characters.'
  Enabled: true
  Max: 120
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 155

Metrics/ClassLength:
  Max: 250

Style/BlockLength:
  Exclude:
    - 'spec/*.rb'

Metrics/AbcSize:
  Enabled: false
